### ISSUE TITLE
src/adc_mcp3x6x.h

### ISSUE THREAD

**Issue by nerdyscout** [fietser28/EL-Load-FW#3]
first of all I think there can not betwo license references:

```
// SPDX-License-Identifier: GPL-3.0-or-later
// SPDX-License-Identifier: MIT
```

more importanly it seems to be copied from https://github.com/nerdyscout/Arduino_MCP3x6x_Library

**Comment by fietser28** [comment]
My apologies. You are correct.

Do you think it is correct now?

**Comment by nerdyscout** [comment]
thanks for your quick reply.
fine for me :)
